package cn.zzh.foreground_client.project.entity;

import java.math.BigDecimal;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.serial_id
     *
     * @mbggenerated
     */
    private String serialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_locked
     *
     * @mbggenerated
     */
    private Byte isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_noob
     *
     * @mbggenerated
     */
    private Byte isNoob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profit
     *
     * @mbggenerated
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbggenerated
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbggenerated
     */
    private Long updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User(Long id, String serialId, String phoneNumber, String idCard, String realName, Byte isLocked, Byte isNoob, String password, String salt, BigDecimal balance, BigDecimal profit, Long createdAt, Long updatedAt) {
        this.id = id;
        this.serialId = serialId;
        this.phoneNumber = phoneNumber;
        this.idCard = idCard;
        this.realName = realName;
        this.isLocked = isLocked;
        this.isNoob = isNoob;
        this.password = password;
        this.salt = salt;
        this.balance = balance;
        this.profit = profit;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public User(long id,String phoneNumber){
        this.id=id;
        this.phoneNumber=phoneNumber;
    }

    public User(String phoneNumber,String password,String salt){
        this.phoneNumber=phoneNumber;
        this.password=password;
        this.salt=salt;
    }


    public User(String phoneNumber,String password){
        this.phoneNumber=phoneNumber;
        this.password=password;
    }

    public User(String phoneNumber){
        this.phoneNumber=phoneNumber;
    }

    public User(){

    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", serialId='" + serialId + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", idCard='" + idCard + '\'' +
                ", realName='" + realName + '\'' +
                ", isLocked=" + isLocked +
                ", isNoob=" + isNoob +
                ", password='" + password + '\'' +
                ", salt='" + salt + '\'' +
                ", balance=" + balance +
                ", profit=" + profit +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}'+"\n";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSerialId() {
        return serialId;
    }

    public void setSerialId(String serialId) {
        this.serialId = serialId;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Byte getIsLocked() {
        return isLocked;
    }

    public void setIsLocked(Byte isLocked) {
        this.isLocked = isLocked;
    }

    public Byte getIsNoob() {
        return isNoob;
    }

    public void setIsNoob(Byte isNoob) {
        this.isNoob = isNoob;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public BigDecimal getProfit() {
        return profit;
    }

    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
}